name: Build RobotFramework AIO packages

on:
  push:
    tags:
      - "rel/aio/*.*.*.*"
      - "dev/aio/*.*.*.*"
  pull_request:
    types:
      - closed
    branches: 
      - develop
  workflow_dispatch:

env:
  TRIGGER_BY: ${{ github.ref_type }}
  TAG_NAME: ${{ github.ref_name }}
  REF_NAME: ${{ github.ref_name }}
  DEFAULT_REF: ${{ github.base_ref }}
  DOCBUILDER_ARGUMENTS: --configfile "./maindoc_configs/maindoc_config_OSS.json"

jobs:
  tag-repos:
    name: Tag all related repositories
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install dependencies
      run: python -m pip install -r ./tools/git-tag/requirements.txt

    - name: Tag repositories
      run: python ./tools/git-tag/git-tag.py "$TAG_NAME" ./config/repositories/tag_repos.json

  build-linux:
    name: Build Linux package
    runs-on: ubuntu-latest
    needs: tag-repos
    # if: always() && needs.tag-repos.result != 'failure' && needs.tag-repos.result != 'cancelled'
    if: ${{ ! failure() && ! cancelled() }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          chmod +x ./requirements_linux.sh
          ./requirements_linux.sh

      - name: Clone repositories
        run: |
          chmod +x ./cloneall
          ./cloneall

      - name: Install
        run: |
          chmod +x ./install/install.sh
          ./install/install.sh

      - name: Build
        run: |
          chmod +x ./build
          ./build

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: linux-package
          path: output_lx/*.deb

  build-windows:
    name: Build Windows package
    runs-on: windows-latest
    env:
      GENDOC_LATEXPATH: C:/texlive/2022/bin/win32
    steps:
      - name: Support long path in git
        run: git config --system core.longpaths true

      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: ./requirements_windows.sh

      - name: Clone repositories
        shell: bash
        run: ./cloneall

      - name: Install
        shell: bash
        run: ./install/install.sh

      - name: Build
        shell: bash
        run: ./build

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: windows-package
          path: Output/

  install-test-windows:
    name: Test Windows package
    runs-on: windows-latest
    needs: build-windows
    env:
      RobotPythonPath: "C:/Program Files/RobotFramework/python39"
      RobotTutorialPath: "C:/RobotTest/tutorial"

    steps:
    - name: Support long path in git
      run: git config --system core.longpaths true

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Clone repositories
      shell: bash
      run: ./cloneall

    - name: Download Windows installer package
      uses: actions/download-artifact@v3
      with:
        name: windows-package

    - name: Install RobotFramework AIO on Windows
      shell: cmd
      run: ./scripts/install-windows.bat

    - name: Install pandoc on Windows
      shell: cmd
      run: choco install pandoc

    - name: Run tests on Windows
      shell: cmd
      run: |
        set Robot
        "%RobotPythonPath%/python" test/aio-test-trigger/aio-test-trigger.py

  install-test-linux:
    name: Test Linux package
    runs-on: ubuntu-latest
    needs: build-linux

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Clone repositories
      run: |
        chmod +x ./cloneall
        ./cloneall

    - name: Download Linux installer package
      uses: actions/download-artifact@v3
      with:
        name: linux-package

    - name: Install on Linux
      run: sudo apt-get install ./*.deb

    - name: Run tests on Linux
      run: |
        . /opt/rfwaio/linux/set_robotenv.sh
        printenv | grep Robot
        echo $(which pandoc)
        $RobotPythonPath/python3.9 test/aio-test-trigger/aio-test-trigger.py

  release:
    name: Release AIO
    runs-on: ubuntu-latest
    needs: [install-test-windows, install-test-linux]
    if: github.ref_type == 'tag'

    steps:
    - name: Download artifact from build workflow
      uses: actions/download-artifact@v3

    - name: Get released file names
      run: |
        echo "EXE_FILE=$(ls windows-package/*.exe | head -1)" >> $GITHUB_ENV
        echo "DEB_FILE=$(ls linux-package/*.deb | head -1)" >> $GITHUB_ENV
        echo "RELEASE_VERSION=${TAG_NAME#rel/aio/}" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: RobotFramework AIO version ${{ env.RELEASE_VERSION }}
        draft: false
        prerelease: false

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.EXE_FILE }}
        asset_name: setup_RobotFramework_AIO_Win_${{ env.RELEASE_VERSION }}.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.DEB_FILE }}
        asset_name: setup_RobotFramework_AIO_Linux_${{ env.RELEASE_VERSION }}.deb
        asset_content_type: application/vnd.debian.binary-package
